### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [shepherdingelectrons/ATtiny85Mario#1]
Hello!

I found link to this project from https://hackaday.com/2020/10/14/tiny-mario-clone-on-a-tiny-processor/

Could you please add information about license of this repository — is it allowed to copy, change and use code in any purpose?
It would be great to see any popular open source license.

If code is based on https://github.com/bitbank2/oled_turbo which is GPLv3, then probably this project should be GPLv3 too.

**Comment by shepherdingelectrons** [comment]
Hello there!

Thanks for raising this issue, I've now added the GPLv3 license to the repository :-)

**Comment by vazhnov** [comment]
@shepherdingelectrons , thank you!!!
